name: Firebase deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Run deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js application
        uses: actions/setup-node@v4
        with:
          version: latest

      - name: Install dependencies
        run: npm install

      - name: make deploy
        run: npm run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}